# Generated by Django 5.2.6 on 2025-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrier',
            name='categorie',
            field=models.CharField(choices=[('plombier', 'Plombier'), ('electricite', 'Electricité'), ('menage', 'Ménage'), ('jardinage', 'Jardinage')], default='plombier', max_length=20),
        ),
    ]
