# Generated by Django 5.2.6 on 2025-10-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ouvrier_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='message_negotiation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='ouvrier_assigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to='api.ouvrier'),
        ),
        migrations.AddField(
            model_name='demande',
            name='prix_negocie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('enAttente', 'En Attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('enNegociation', 'En Négociation'), ('confirmee', 'Confirmée')], default='enAttente', max_length=15),
        ),
    ]
