# Generated by Django 5.2.6 on 2025-10-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_demande_message_negotiation_demande_ouvrier_assigne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ouvrier',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
