# Generated by Django 5.2.6 on 2025-10-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_fcm_token_ouvrier_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('enAttente', 'En Attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('enNegociation', 'En Négociation'), ('confirmee', 'Confirmée')], default='confirmee', max_length=15),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('confirmee', 'Confirmée'), ('enRoute', 'En Route'), ('enCours', 'En Cours'), ('terminee', 'Terminée')], default='enAttente', max_length=15),
        ),
    ]
