# Generated by Django 5.2.6 on 2025-10-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_commande_etat_alter_demande_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='latitude',
            new_name='prix_negocie',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='prix_negocie',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='message_negotiation',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='ouvrier_assigne',
        ),
        migrations.AddField(
            model_name='commande',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='demande',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('enAttente', 'En Attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('enNegociation', 'En Négociation'), ('confirmee', 'Confirmée')], default='enAttente', max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('enAttente', 'En Attente'), ('confirmee', 'Confirmée'), ('enRoute', 'En Route'), ('enCours', 'En Cours'), ('terminee', 'Terminée')], default='enAttente', max_length=20),
        ),
    ]
