# Generated by Django 5.2.6 on 2025-10-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_latitude_commande_prix_negocie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('enAttente', 'En Attente'), ('confirmee', 'Confirmée'), ('enRoute', 'En Route'), ('enCours', 'En Cours'), ('terminee', 'Terminée'), ('failed', 'Failed')], default='enAttente', max_length=20),
        ),
    ]
